services:
  database:
    image: mysql:5.7
    container_name: database
    restart: always
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=users-crud-test