services:
  backend:
    image: node:18-alpine
    working_dir: /app
    container_name: backend
    command: sh -c "npm run dev"
    stdin_open: true
    tty: true
    env_file:
      - ../.env.development
    volumes:
      - ../:/app
    ports:
      - 8080:8080
    expose:
      - 8080